# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160723_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='abstract',
            field=models.TextField(blank=True),
        ),
    ]
